services:
  test_db:
    container_name: 'pytest_trainings_db'
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - "5439:5432"
    networks:
      - test_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${TEST_POSTGRES_USER}", "-d", "${TEST_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test_app:
    container_name: 'pytest_trainings_app'
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      test_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://test_db_user:test_db_password@test_trainings_db:5432/test_db"
    networks:
      - test_network
    command: >
      bash -c "
      poetry install &&
      poetry run pytest"

networks:
  test_network:
    driver: bridge
