services:
  db:
    container_name: trainings_db
    image: postgres:16.4
    restart: always
    env_file: .env
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  migrations:
    build:
      context: .
      dockerfile: ./docker/migrations/Dockerfile
    depends_on:
      - db
    command: >
      bash -c "
      sleep 5 &&
      python migrations/apply_migrations.py"
    env_file: .env
    networks:
      - app_network
    restart: "no"

  app:
    container_name: trainings_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - migrations
    env_file: .env
    ports:
      - "8080:8000"
    command: >
      bash -c "
      poetry install --no-dev &&
      uvicorn trainings_app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/trainings_app
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge