services:
  test_db:
    container_name: 'test_trainings_db'
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - "5439:5432"
    networks:
      - test_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${TEST_POSTGRES_USER}", "-d", "${TEST_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pytest_run:
    container_name: 'pytest_run_container'
    image: python:3.10
    depends_on:
      test_db:
        condition: service_healthy
    command: >
      bash -c "sleep 15 && pip install poetry && poetry install
      && pytest -k 'tests/repositories/test_clients.py' 
      && pytest -k 'tests/repositories/test_memberships.py' 
      && pytest -k 'tests/repositories/test_clients.py'"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge